# 

In [ ]:
!pip install numpy


In [ ]:
import numpy as np
a = [[1,2,3],[4,5,6],[7,8,9]]
A = np.array(a)
print(A)
print(A.shape)



In [ ]:
A=np.ones([3,2])
A.astype("int")

In [ ]:
A.astype("int")

In [ ]:
A

In [ ]:
np.ones([4,5])

In [ ]:
A=np.array(range(1,10,2))
print(A)
B=np.arange(1,10,3)
print(B)
C=np.linspace(1,10,3)
print(C)

In [ ]:
list(range(0,10))

In [ ]:
np.array(range(0,10,2))

In [ ]:
A= np.random.randint(-10,10,(3,4))
print(A)
print(A.dtype,A.shape,A.size)
A=A.reshape(4,3)
print("reshaped A:\n",A)
A[1,:]
A[:,1]

In [ ]:
A= np.random.randint(5,15,(2,3,3))
print(A)
print(A.dtype,A.shape,A.size)
A=A.reshape(2,3,3)
print("reshaped A:\n",A)
A[1,1]
A[1,1]

In [ ]:
A[:,2, :]

In [ ]:
# you need to create a 1D Numpy array of length  365(daily temperatures)
    into a 2D array with 52 full weeks of 7 days each,discarding the remaining days.

In [12]:
import numpy as np
A= np.random.randint(1,30,(365))
print(A.shape)
B=A[:52*7].reshape(52,7)#slice;theb reshape the slice
print("reshaped A:\n",B)
B.size,B.shape


(365,)
reshaped A:
 [[ 1  1 18 24 27 15  3]
 [21 13  8 26 18 23  7]
 [ 7 29  2 14 20 26 17]
 [11 29  7  9 16  8  9]
 [ 2 17 18 27 24  4 29]
 [20  9  8 27 11  1 27]
 [10 27 18  7  6  3 20]
 [23 10 17 24 18 15 24]
 [14  5 18 25 14 25 11]
 [29  5 10  6 23 29 23]
 [25 27 20 28  8  9  7]
 [18 23 28 13 22 11 27]
 [ 8 12 22 12  8 16 28]
 [ 6  8 14  8 15  5 26]
 [ 8 14  2  5  1 21  5]
 [15  6 27 16 14 15 11]
 [28 11 22 15 29  7 18]
 [10 10  8 16  6 26  6]
 [ 3  8  6 17  7  9  3]
 [12 17  7 17 16 24  7]
 [28 19 12  7 12 12 24]
 [ 3 13  8 21 27 19  7]
 [ 3 13  9 13 13  7 23]
 [24 18 10 25  4 29 21]
 [11 18 21 14  5 10 27]
 [21 14 16  5  9 26 27]
 [23  1 28 28 21  3 10]
 [11 19 28 20  2 15 27]
 [19  3 19 22  5 23 12]
 [21 20 17  1 23  2 18]
 [ 3  4 25  1  3 20  7]
 [ 5 17 29 11 26  8  5]
 [12  9 25  4  2  9 12]
 [26 14 10 16 24 14  5]
 [ 8 19 17  6 12  6 24]
 [11  9  7 18  3 21 20]
 [ 2  3  4 23 16 23  2]
 [18 22  9 28 16  9 17]
 [28  8 10 11 19 13  2]
 [20 18  8 14 24 18  2]
 [16 13 27  3  2 22 

(364, (52, 7))

In [12]:
import numpy as np
A= np.random.randint(1,30,(365))
print(A.shape)
B=A[:52*7].reshape(52,7)#slice;theb reshape the slice
print("reshaped A:\n",B)
B.size,B.shape


(365,)
reshaped A:
 [[ 1  1 18 24 27 15  3]
 [21 13  8 26 18 23  7]
 [ 7 29  2 14 20 26 17]
 [11 29  7  9 16  8  9]
 [ 2 17 18 27 24  4 29]
 [20  9  8 27 11  1 27]
 [10 27 18  7  6  3 20]
 [23 10 17 24 18 15 24]
 [14  5 18 25 14 25 11]
 [29  5 10  6 23 29 23]
 [25 27 20 28  8  9  7]
 [18 23 28 13 22 11 27]
 [ 8 12 22 12  8 16 28]
 [ 6  8 14  8 15  5 26]
 [ 8 14  2  5  1 21  5]
 [15  6 27 16 14 15 11]
 [28 11 22 15 29  7 18]
 [10 10  8 16  6 26  6]
 [ 3  8  6 17  7  9  3]
 [12 17  7 17 16 24  7]
 [28 19 12  7 12 12 24]
 [ 3 13  8 21 27 19  7]
 [ 3 13  9 13 13  7 23]
 [24 18 10 25  4 29 21]
 [11 18 21 14  5 10 27]
 [21 14 16  5  9 26 27]
 [23  1 28 28 21  3 10]
 [11 19 28 20  2 15 27]
 [19  3 19 22  5 23 12]
 [21 20 17  1 23  2 18]
 [ 3  4 25  1  3 20  7]
 [ 5 17 29 11 26  8  5]
 [12  9 25  4  2  9 12]
 [26 14 10 16 24 14  5]
 [ 8 19 17  6 12  6 24]
 [11  9  7 18  3 21 20]
 [ 2  3  4 23 16 23  2]
 [18 22  9 28 16  9 17]
 [28  8 10 11 19 13  2]
 [20 18  8 14 24 18  2]
 [16 13 27  3  2 22 

(364, (52, 7))

In [15]:
A= np.random.randint(1,30,(365))
print(A.shape)

B=A[:52*7].reshape(52,7)
52*7

(365,)


364

In [16]:
#you have a 2D array data of shape (1000,3)storing x,y,z acceleration readings for 1000 timesteps.you want the mean acceleration in each axis.
which command is most appropriate

In [17]:
A= np.random.randint(50,100,(1000,3))
print(A)

[[64 93 61]
 [93 54 90]
 [86 77 61]
 ...
 [96 80 90]
 [75 97 63]
 [56 67 72]]


In [27]:
A= np.array([[1,2,3],[4,5,6]])
print(A.size,A.shape)
print(A)

6 (2, 3)
[[1 2 3]
 [4 5 6]]


In [28]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
A.mean()

np.float64(3.5)

In [41]:
A.mean(axis=2)

array([[ 1.5,  5.5,  9.5],
       [13.5, 17.5, 21.5]])

In [38]:
A= np.arange(0,24).reshape(2,3,4)
print (A)
a=A.mean(axis=1)
b=A.mean()
print (b)
print (a)
print (a.shape)
print(a.size)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
11.5
[[ 4.  5.  6.  7.]
 [16. 17. 18. 19.]]
(2, 4)
8


In [ ]:
#YOU HAVE A 1d array freq contains frequencies in hertz


In [42]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
A.shape

(2, 3)

In [52]:
B = np.random.randint(0,10,(2,3,4))

In [53]:
B

array([[[1, 1, 1, 0],
        [1, 7, 7, 7],
        [8, 8, 1, 6]],

       [[0, 6, 7, 0],
        [4, 9, 2, 7],
        [4, 4, 7, 7]]], dtype=int32)

In [47]:
B.shape

(2, 3, 4)

In [58]:
B.sum(axis=2)


array([[ 3, 22, 23],
       [13, 22, 22]])

In [59]:
#!pip install matplotlib

In [ ]:

#plt.hist

In [61]:
np.sin(B)

array([[[ 0.84147098,  0.84147098,  0.84147098,  0.        ],
        [ 0.84147098,  0.6569866 ,  0.6569866 ,  0.6569866 ],
        [ 0.98935825,  0.98935825,  0.84147098, -0.2794155 ]],

       [[ 0.        , -0.2794155 ,  0.6569866 ,  0.        ],
        [-0.7568025 ,  0.41211849,  0.90929743,  0.6569866 ],
        [-0.7568025 , -0.7568025 ,  0.6569866 ,  0.6569866 ]]])

In [62]:
np.cos(B),np.tanh(B)

(array([[[ 0.54030231,  0.54030231,  0.54030231,  1.        ],
         [ 0.54030231,  0.75390225,  0.75390225,  0.75390225],
         [-0.14550003, -0.14550003,  0.54030231,  0.96017029]],
 
        [[ 1.        ,  0.96017029,  0.75390225,  1.        ],
         [-0.65364362, -0.91113026, -0.41614684,  0.75390225],
         [-0.65364362, -0.65364362,  0.75390225,  0.75390225]]]),
 array([[[0.76159416, 0.76159416, 0.76159416, 0.        ],
         [0.76159416, 0.99999834, 0.99999834, 0.99999834],
         [0.99999977, 0.99999977, 0.76159416, 0.99998771]],
 
        [[0.        , 0.99998771, 0.99999834, 0.        ],
         [0.9993293 , 0.99999997, 0.96402758, 0.99999834],
         [0.9993293 , 0.9993293 , 0.99999834, 0.99999834]]]))

In [65]:
#Q)YOU HAVE A 1D ARRAY FREQ CONTAINING FREQUENCIES IN HERTZ .YOU WANT A ABOOLEAN MASK THAT SELECTS ALL ENTRIES IN THE RANGE 100<=F,=1000.WHICH EXPRESSIONS
#IS MOST APPROPRIATE?

In [66]:
B[B>4]

array([7, 7, 7, 8, 8, 6, 6, 7, 9, 7, 7, 7], dtype=int32)

In [67]:
B

array([[[1, 1, 1, 0],
        [1, 7, 7, 7],
        [8, 8, 1, 6]],

       [[0, 6, 7, 0],
        [4, 9, 2, 7],
        [4, 4, 7, 7]]], dtype=int32)

In [68]:
B.shape,B

((2, 3, 4),
 array([[[1, 1, 1, 0],
         [1, 7, 7, 7],
         [8, 8, 1, 6]],
 
        [[0, 6, 7, 0],
         [4, 9, 2, 7],
         [4, 4, 7, 7]]], dtype=int32))

In [78]:
B= np.random.randint(2,2000,100)

In [79]:
B.shape,B

((100,),
 array([1580, 1403, 1845,  265,  594, 1661, 1591, 1712,  928,  382,  907,
        1445, 1109,  237,  747,  875,  133, 1758, 1263, 1542, 1276, 1948,
         305, 1990,  703,  742,  379,  603, 1844,  492, 1600,  772, 1363,
        1925,  575,  651, 1620, 1110, 1585, 1148, 1093,  935,  163, 1899,
         827, 1221, 1473, 1979,  762, 1387,  405,  505,  543, 1296, 1668,
        1486,  907,  931,  425, 1663, 1769, 1985,  850,  500, 1795, 1954,
        1596,  854, 1476, 1878,  321, 1831, 1613, 1495,  477, 1739,  754,
         819, 1756,   45, 1791, 1665, 1624,  132, 1884, 1626,  849, 1360,
         364, 1368,  161, 1265, 1341, 1486, 1080,  303, 1109,  998, 1392,
        1356], dtype=int32))

In [98]:
w=B[B>=100]

In [100]:
w[w<=1000]

array([265, 594, 928, 382, 907, 237, 747, 875, 133, 305, 703, 742, 379,
       603, 492, 772, 575, 651, 935, 163, 827, 762, 405, 505, 543, 907,
       931, 425, 850, 500, 854, 321, 477, 754, 819, 132, 849, 364, 161,
       303, 998], dtype=int32)

In [108]:
True&False

False

In [110]:
#stack two arrays of shape 3*4 and 3*3
A= np.random.randint(0,10,(3,4))
B=np.random.randint(0,10,(3,4))
print(A,'\n\n',B,'\n')
C= np.stack((A,B))
print(C)
print(C.shape)
            

[[6 0 0 9]
 [9 1 3 2]
 [7 7 0 3]] 

 [[8 4 5 7]
 [5 4 6 4]
 [6 9 7 3]] 

[[[6 0 0 9]
  [9 1 3 2]
  [7 7 0 3]]

 [[8 4 5 7]
  [5 4 6 4]
  [6 9 7 3]]]
(2, 3, 4)


In [121]:
A= np.random.randint(0,10,(3,4))
B=np.random.randint(0,10,(3,4))
print(A,'\n\n',B)
np.vstack((A,B))

[[6 5 4 1]
 [6 0 9 1]
 [2 5 6 7]] 

 [[4 7 3 8]
 [7 9 0 4]
 [8 0 7 0]]


array([[6, 5, 4, 1],
       [6, 0, 9, 1],
       [2, 5, 6, 7],
       [4, 7, 3, 8],
       [7, 9, 0, 4],
       [8, 0, 7, 0]], dtype=int32)

In [122]:
np.hstack((A,B))

array([[6, 5, 4, 1, 4, 7, 3, 8],
       [6, 0, 9, 1, 7, 9, 0, 4],
       [2, 5, 6, 7, 8, 0, 7, 0]], dtype=int32)

In [124]:
np.concatenate((A,B),axis=1)

array([[6, 5, 4, 1, 4, 7, 3, 8],
       [6, 0, 9, 1, 7, 9, 0, 4],
       [2, 5, 6, 7, 8, 0, 7, 0]], dtype=int32)

In [125]:
print(A)

[[6 5 4 1]
 [6 0 9 1]
 [2 5 6 7]]
